### ISSUE TITLE
how to use your code?

### ISSUE THREAD

**Issue by hanbeibei** [wiredmax/atlassian-stash-git-ssh-proxy#1]
hello, 

I got your repo by google.

i want to get contact with stash via python, but it fails due to proxy problem..

Could you share me how to your your code? it might be halpful.

Great appreciate
Beibei

**Comment by wiredmax** [comment]
This proxy server needs NodeJS to be installed to run. (https://nodejs.org) and the npm dependencies installed by running `npm install` in the root of the cloned repo.

One you have NodeJS installed and cloned the repo all you have to do is `npm install` then run `node server.js`

The proxy server will not persist this way, because it's running from your console, so you can run it using PM2 (https://github.com/Unitech/pm2) or forever (https://github.com/foreverjs/forever) and enable persistence. 

This is code is really basic and you could use something like this by using HAProxy to proxy TCP on 7999 to 22 also.
